name: Redmi-AX6000-padavanonly

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-23.05
  REPO_BRANCH: openwrt-23.05
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: padavanonly/Redmi-AX6000/.config
  DIY_P1_SH: padavanonly/Redmi-AX6000/diy-part1.sh
  DIY_P2_SH: padavanonly/Redmi-AX6000/diy-part2.sh
  SSH_ACTIONS: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  OPENWRT_NAME: padavanonly

jobs:
  build:
    runs-on: ubuntu-22.04  # ä½¿ç”¨ Ubuntu 22.04 ç³»ç»Ÿ

    steps:
    - name: æ£€æŸ¥é¡¹ç›®åˆ†æ”¯
      uses: actions/checkout@main

    - name: åˆå§‹åŒ–ç¼–è¯‘ç¯å¢ƒ
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        # æ¸…ç†ç³»ç»Ÿå¹¶å‡çº§è½¯ä»¶åŒ…
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq upgrade -y
        sudo -E apt-get -qq install necessary packages...

    - name: å®‰è£… Go 1.22.5
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: éªŒè¯ Go ç‰ˆæœ¬
      run: go version
        
    - name: ä¸‹è½½å›ºä»¶æºç 
      working-directory: /workdir
      run: |
        # å…‹éš† OpenWrt ä»“åº“
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        # åˆ›å»ºåˆ° openwrt ç›®å½•çš„ç¬¦å·é“¾æ¥
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
         
    - name: åŠ è½½ feeds.conf.default & DIY_P1_SH
      run: |
        # å¤åˆ¶ feeds.conf.default
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF $GITHUB_WORKSPACE/openwrt/feeds.conf.default
        # æ‰§è¡Œ diy-part1.sh è„šæœ¬
        chmod +x $DIY_P1_SH
        cd $GITHUB_WORKSPACE/openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH
        
    - name: æ›´æ–° & å®‰è£… feeds
      run: |
        cd $GITHUB_WORKSPACE/openwrt
        ./scripts/feeds update -a
        rm -rf feeds/packages/lang/golang
        git clone https://github.com/kenzok8/golang feeds/packages/lang/golang
        
    - name: æ›´æ–°å’Œæ›¿æ¢æ’ä»¶
      run: |
        cd $GITHUB_WORKSPACE/openwrt
        # åˆ é™¤æ—§çš„ Openclash æ–‡ä»¶
        rm -rf feeds/luci/applications/luci-app-openclash
        mv feeds/kenzok8/luci-app-openclash feeds/luci/applications/luci-app-openclash
        # æ›¿æ¢ msd_lite æ’ä»¶
        rm -rf feeds/packages/net/msd_lite
        git clone https://github.com/gyssi007/msd_lite.git feeds/packages/net/msd_lite
        # æ›¿æ¢ luci-app-msd_lite æ’ä»¶
        rm -rf feeds/luci/applications/luci-app-msd_lite
        git clone https://github.com/gyssi007/luci-app-msd_lite.git feeds/luci/applications/luci-app-msd_lite
        # æ›´æ–° feeds å¹¶å®‰è£…
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: åŠ è½½ config & DIY_P2_SH
      run: |
        # å¤åˆ¶è‡ªå®šä¹‰é…ç½®æ–‡ä»¶
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE $GITHUB_WORKSPACE/openwrt/.config
        # æ‰§è¡Œ diy-part2.sh è„šæœ¬
        chmod +x $DIY_P2_SH
        cd $GITHUB_WORKSPACE/openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH
        
    - name: SSHé“¾æ¥ç®¡ç†
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: ä¸‹è½½å®‰è£…åŒ…
      id: package
      run: |
        cd $GITHUB_WORKSPACE/openwrt
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: ç¼–è¯‘å›ºä»¶
      id: compile
      run: |
        cd $GITHUB_WORKSPACE/openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        # è·å–è®¾å¤‡åç§°å’Œç›®æ ‡åç§°
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=$(cat DEVICE_NAME)" >> $GITHUB_ENV
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*TARGET_.*_(.*)_DEVICE_.*=y/\1/' > TARGET_NAME
        [ -s TARGET_NAME ] && echo "TARGET_NAME=$(cat TARGET_NAME)" >> $GITHUB_ENV
        # è®¾ç½®å›ºä»¶æ–‡ä»¶å
        echo "FILE_DATE=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: æŸ¥çœ‹ç£ç›˜ä½¿ç”¨æƒ…å†µ
      if: (!cancelled())
      run: df -hT

    - name: æ•´ç†æ–‡ä»¶å¹¶é‡å‘½å
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: | 
        cd $GITHUB_WORKSPACE/openwrt/bin/targets/*/*
        rm -rf packages
        sudo -E apt-get -qq install rename
        rename 's/.*${{ env.TARGET_NAME }}/${{ env.FILE_DATE }}-${{ env.OPENWRT_NAME }}/' *
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
       
    - name: ä¸Šä¼ å›ºä»¶åˆ° GitHub
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.FILE_DATE }}-${{ env.OPENWRT_NAME }}-${{ env.DEVICE_NAME }}
        path: ${{ env.FIRMWARE }}

    - name: ç”Ÿæˆ Release æ ‡ç­¾
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=${{ env.FILE_DATE }}-${{ env.OPENWRT_NAME }}-${{ env.DEVICE_NAME }}" >> $GITHUB_OUTPUT
        touch release.txt
        echo "ç”±è¡·æ„Ÿè°¢æ‰€æœ‰ä¸º OpenWrt æ— ç§å¥‰çŒ®çš„å¤§ä½¬ä»¬" >> release.txt
        echo "ğŸ“¥ å›ºä»¶ä¸‹è½½" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: å‘å¸ƒè‡³ GitHub Release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: release.txt
